

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_storage:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:v1.13.2
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    environment:
      OLLAMA_MODELS: "/root/.ollama/models"
    volumes:
      - ollama_storage:/root/.ollama

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    environment:
      N8N_HOST: ${N8N_HOSTNAME}
      N8N_PORT: ${N8N_PORT_HTTP}
      N8N_PROTOCOL: https
      N8N_PORT_HTTPS: ${N8N_PORT_HTTPS}
      N8N_SSL_CERT: ${SSL_CERT_PATH}
      N8N_SSL_KEY: ${SSL_KEY_PATH}
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: ${POSTGRES_HOST}
      DB_POSTGRESDB_PORT: ${POSTGRES_PORT}
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${N8N_PORT_HTTP}:5678"
      - "${N8N_PORT_HTTPS}:443"
    volumes:
      - ./certs:/certs
      - n8n_storage:/home/node/.n8n

volumes:
  postgres_storage:
  qdrant_storage:
  ollama_storage:
  n8n_storage:
